name: Test push

on:
  push:
    branches: [ '*' ]

jobs:
  push:
    runs-on: ubuntu-latest
    container: python:3.11-alpine

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install .
      - run: |
          VERSION=$(python -c 'from mkdocs_git_range import __version__ as version; print(version)')
          echo "VERSION=${VERSION}"
