name: Test push

on:
  push:
    branches: [ '*' ]

jobs:
  push:
    runs-on: ubuntu-latest
    container: python:3.11-alpine

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install .
      - run: python -c 'print(mkdocs_git_range.__version__)'
