on:
  push:
    branches: ["*"]
jobs:
  checkout:
    runs-on: [ubuntu-latest]
    container: squidfunk/mkdocs-material
    steps:
      - uses: actions/checkout@v4
        with:
          repository: DevOpsJeremy/DevOpsJeremy.github.io
        if: "'a' == 'b'"
      - name: Build
        run: mkdocs build