name: Publish Python package

on:
  push:
    branches: [ $default-branch ]
    paths: [ src/** ]

jobs:
  release:
    name: New release
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Update version
        run: |
          VERSION=$NEXT_VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          gh variable set VERSION -b $VERSION
          NEXT_VERSION=$(echo $NEXT_VERSION | awk -F. -v OFS=. '{$NF += 1; print}')
          gh variable set NEXT_VERSION -b $NEXT_VERSION

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install build .

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create release
        run: |
          gh release create $VERSION --title $VERSION --generate-notes --target $GITHUB_REF_NAME
          gh release upload $VERSION dist/*
